Repository indigo-iam/iam, pull requests merged in 2024-07, with the labels that each got.

#802 Send an email when client status changes
  iam-login-service/src/main/java/it/infn/mw/iam/api/client/management/service/DefaultClientManagementService.java
  iam-login-service/src/main/java/it/infn/mw/iam/notification/NotificationFactory.java
  iam-login-service/src/main/java/it/infn/mw/iam/notification/TransientNotificationFactory.java
  iam-login-service/src/main/resources/email-templates/clientStatusChanged.ftl
  iam-login-service/src/test/java/it/infn/mw/iam/test/service/client/ClientManagementServiceTests.java
  iam-persistence/src/main/java/it/infn/mw/iam/core/IamNotificationType.java
  iam-persistence/src/main/resources/db/migration/test/V100000___test_data.sql
Labels: status/changes-requested

#793 Add groups enrollment logic to be applied after users registration
  iam-login-service/src/main/java/it/infn/mw/iam/config/IamProperties.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/user/DefaultIamAccountService.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/service/IamAccountServiceTests.java
Labels: status/in-review

#814 Refresh token flow not allowed for suspended clients
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/RefreshTokenGranterTests.java
  pom.xml
Labels: status/done

#822 Update angular-jwt script link
  iam-test-client/src/main/resources/templates/index.html
Labels: status/in-review, priority/high
