Repository indigo-iam/iam, pull requests merged in 2024-09, with the labels that each got.

#835 Add devcontainer configuration
  .devcontainer/h2/devcontainer.json
  .devcontainer/mysql/compose.yaml
  .devcontainer/mysql/devcontainer.json
  .mvn/cnaf-mirror-settings.xml
  .mvn/maven.config
Labels: kind/task, status/in-review

#838 Track refresh tokens in access token AUDIT logs
  iam-login-service/src/main/java/it/infn/mw/iam/audit/events/tokens/AccessTokenIssuedEvent.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/RefreshTokenGranterTests.java
Labels: kind/debt, status/in-review

#849 Fix expected password min length to 8 chars
  iam-login-service/src/main/java/it/infn/mw/iam/util/RegexUtil.java
  iam-login-service/src/main/webapp/resources/iam/apps/dashboard-app/directives/password.directive.js
  iam-login-service/src/main/webapp/resources/iam/js/directive/password.directive.js
  iam-login-service/src/test/java/it/infn/mw/iam/test/api/account/password/PasswordUpdateTests.java
Labels: kind/bug, status/in-review
