Repository indigo-iam/iam, pull requests merged in 2025-04, with the labels that each got.

#943 Return the number of active users from the stats endpoint
  iam-login-service/src/main/java/it/infn/mw/iam/core/IamStatisticalEndpoint.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/StatsEndpointResponse.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/core/IamStatisticalEndpointTests.java
  iam-persistence/src/main/java/it/infn/mw/iam/persistence/repository/IamAccountRepository.java
Labels: status/done

#950 Fix missing delete label event
  iam-login-service/src/main/java/it/infn/mw/iam/core/user/DefaultIamAccountService.java
Labels: kind/debt, status/done

#916 Add support for resource parameter
  .github/workflows/maven.yml
  .github/workflows/sonar.yaml
  iam-login-service/src/main/java/it/infn/mw/iam/config/MitreServicesConfig.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/error/InvalidResourceError.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/oauth/IamDeviceEndpointController.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/oauth/IamOAuth2RequestFactory.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/oauth/IamOAuthConfirmationController.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/oauth/profile/common/BaseAccessTokenBuilder.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/oauth/profile/wlcg/WLCGProfileAccessTokenBuilder.java
  iam-login-service/src/main/webapp/WEB-INF/views/iam/approveClient.jsp
  iam-login-service/src/main/webapp/WEB-INF/views/iam/approveDevice.jsp
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/EndpointsTestUtils.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/ResourceIndicatorTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/authzcode/AuthorizationCodeIntegrationTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/profile/WLCGProfileIntegrationTests.java
  iam-test-client/src/main/java/it/infn/mw/tc/IamAuthRequestOptionsService.java
  iam-test-client/src/main/java/it/infn/mw/tc/IamAuthRequestUrlBuilder.java
  iam-test-client/src/main/java/it/infn/mw/tc/IamClientApplicationProperties.java
  iam-test-client/src/main/java/it/infn/mw/tc/IamOIDCClientFilter.java
  iam-test-client/src/main/java/it/infn/mw/tc/IamTestClientConfiguration.java
  iam-test-client/src/main/resources/application.yml
Labels: status/done, priority/normal

#938 Support DER & URL-Encoded PEM client certificates
  iam-login-service/src/main/java/it/infn/mw/iam/api/scim/converter/X509CertificateConverter.java
  iam-login-service/src/main/java/it/infn/mw/iam/authn/x509/DefaultX509AuthenticationCredentialExtractor.java
  iam-login-service/src/main/java/it/infn/mw/iam/authn/x509/PEMX509CertificateChainParser.java
  iam-login-service/src/main/java/it/infn/mw/iam/authn/x509/X509CertificateChainParser.java
  iam-login-service/src/main/java/it/infn/mw/iam/authn/x509/X509CertificateChainParserImpl.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/ext_authn/x509/X509CertificateParserTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/ext_authn/x509/X509CredentialExtractorTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/ext_authn/x509/X509TestSupport.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/scim/converter/ScimX509CertificateConverterTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/scim/updater/factory/DefaultAccountUpdaterFactoryTests.java
  iam-login-service/src/test/resources/x509/test0.cert.der
Labels: status/done

#944 Delete useless forbidden calls from current dashbaord
  iam-login-service/src/main/java/it/infn/mw/iam/api/group/GroupLabelsController.java
  iam-login-service/src/main/webapp/resources/iam/apps/dashboard-app/components/user/groups/user.groups.component.js
  iam-login-service/src/main/webapp/resources/iam/apps/dashboard-app/services/groups.service.js
  iam-login-service/src/test/java/it/infn/mw/iam/test/api/group/GroupLabelTests.java
Labels: kind/task, kind/debt, status/done

#948 Add support to notes being customised
  iam-login-service/src/main/java/it/infn/mw/iam/config/IamProperties.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/DefaultRegistrationRequestService.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/RegistrationRequestDto.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/validation/CernHrDbRequestValidatorService.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/validation/RegistrationFieldsValidationService.java
  iam-login-service/src/main/resources/email-templates/adminHandleRequest.ftl
  iam-login-service/src/main/webapp/resources/iam/apps/registration/registration.controller.js
  iam-login-service/src/main/webapp/resources/iam/apps/registration/registration.html
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/RegistrationFieldsValidationServiceTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/RegistrationUnprivilegedTests.java
  iam-persistence/src/main/java/it/infn/mw/iam/persistence/model/IamRegistrationRequest.java
Labels: status/done

#957 Avoid persisting too long request parameters
  iam-login-service/src/test/java/it/infn/mw/iam/test/ext_authn/x509/X509CertificateParserTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/TokenExchangeTests.java
  pom.xml
Labels: kind/bug, status/done, dependencies, component/mitreid, priority/high

#966 Upgrade dependencies and minor cleanups
  iam-login-service/pom.xml
  iam-login-service/src/main/java/it/infn/mw/iam/api/account/multi_factor_authentication/MultiFactorSettingsDTO.java
  iam-login-service/src/main/java/it/infn/mw/iam/authn/multi_factor_authentication/MfaVerifyController.java
  iam-login-service/src/main/webapp/WEB-INF/views/iam/verify-mfa.jsp
  iam-login-service/src/test/java/it/infn/mw/iam/test/client/management/ClientManagementAPIControllerTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/client/registration/ClientRegistrationAPIControllerTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/ext_authn/x509/X509CertificateParserTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/multi_factor_authentication/MfaVerifyControllerTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/TokenExchangeTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/devicecode/DeviceCodeApprovalTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/oauth/profile/WLCGProfileIntegrationTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/service/client/ClientManagementServiceTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/service/client/ClientRegistrationServiceTests.java
  iam-persistence/pom.xml
  iam-test-client/pom.xml
  iam-voms-aa/pom.xml
  pom.xml
Labels: status/in-review, dependencies, priority/normal

#921 Log the outcome of a VOMS proxy request
  iam-voms-aa/src/main/java/it/infn/mw/voms/api/VOMSController.java
  iam-voms-aa/src/test/resources/application.properties
Labels: kind/task, status/done, priority/high
