Repository indigo-iam/iam, pull requests merged in 2025-08, with the labels that each got.

#997 Configurable text in the registration button
  iam-login-service/src/main/java/it/infn/mw/iam/config/IamProperties.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/web/loginpage/DefaultLoginPageConfiguration.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/web/loginpage/LoginPageConfiguration.java
  iam-login-service/src/main/resources/application.yml
  iam-login-service/src/main/webapp/WEB-INF/tags/iam/page.tag
  iam-login-service/src/main/webapp/WEB-INF/views/iam/login.jsp
  iam-login-service/src/test/java/it/infn/mw/iam/test/login/RegistrationButtonDisabledTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/login/RegistrationButtonTextTests.java
Labels: status/changes-requested

#1024 Add validation when registration fields are read-only
  iam-login-service/src/main/java/it/infn/mw/iam/api/common/LabelDTO.java
  iam-login-service/src/main/java/it/infn/mw/iam/audit/events/account/EmailVerifiedEvent.java
  iam-login-service/src/main/java/it/infn/mw/iam/audit/events/registration/RegistrationAlteredEvent.java
  iam-login-service/src/main/java/it/infn/mw/iam/config/IamProperties.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/user/DefaultIamAccountService.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/user/IamAccountService.java
  iam-login-service/src/main/java/it/infn/mw/iam/core/web/registration/DefaultStartRegistrationController.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/DefaultRegistrationRequestService.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/RegistrationApiController.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/RegistrationRequestDto.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/validation/CernHrDbRequestValidatorService.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/validation/RegistrationFieldsValidationService.java
  iam-login-service/src/main/java/it/infn/mw/iam/util/test/saml/SamlSecurityContextBuilder.java
  iam-login-service/src/main/resources/application-registration.yml
  iam-login-service/src/main/resources/application.yml
  iam-login-service/src/test/java/it/infn/mw/iam/test/api/account/password/PasswordUpdateTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/DefaultFieldsValidationTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/ReadOnlyFieldsValidationTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/RegistrationAttributesTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/RegistrationFieldsValidationServiceTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/RegistrationLifecycleTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/RegistrationPrivilegedTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/RegistrationUnprivilegedTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/RegistrationUsernameTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/UsernameErrorMessageTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/service/IamAccountServiceTests.java
Labels: kind/bug, status/done

#1005 Update affiliation with HR DB
  iam-login-service/src/main/java/it/infn/mw/iam/core/lifecycle/cern/CernHrLifecycleHandler.java
  iam-login-service/src/main/java/it/infn/mw/iam/registration/validation/CernHrDbRequestValidatorService.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/registration/cern/CernTestSupport.java
Labels: status/done

#972 Notify VO Admins when a certificate is added by a user
  iam-login-service/src/main/java/it/infn/mw/iam/api/account_linking/DefaultAccountLinkingService.java
  iam-login-service/src/main/java/it/infn/mw/iam/api/scim/model/ScimX509Certificate.java
  iam-login-service/src/main/java/it/infn/mw/iam/api/scim/provisioning/ScimUserProvisioning.java
  iam-login-service/src/main/java/it/infn/mw/iam/notification/NotificationFactory.java
  iam-login-service/src/main/java/it/infn/mw/iam/notification/NotificationProperties.java
  iam-login-service/src/main/java/it/infn/mw/iam/notification/PersistentNotificationFactory.java
  iam-login-service/src/main/java/it/infn/mw/iam/notification/TransientNotificationFactory.java
  iam-login-service/src/main/resources/application.yml
  iam-login-service/src/main/resources/email-templates/linkedCertificate.ftl
  iam-login-service/src/main/resources/email-templates/unLinkedCertificate.ftl
  iam-login-service/src/test/java/it/infn/mw/iam/test/X509Cert.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/X509Utils.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/audit/event/EventTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/notification/AccountLinkCertificateNotificationTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/scim/me/patch/ScimMeEndpointUtils.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/scim/user/ScimUserProvisioningPatchTests.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/scim/user/ScimUserTestSupport.java
  iam-login-service/src/test/java/it/infn/mw/iam/test/scim/user/x509/ScimX509Tests.java
  iam-persistence/src/main/java/it/infn/mw/iam/core/IamNotificationType.java
Labels: status/in-review, priority/normal
